### ISSUE TITLE
field_name for generated class is sometimes set to a snake case version

### ISSUE THREAD

**Issue by flonou** [mirumee/ariadne-codegen#322]
Hi,

Here is an extract of a schema that I generated code for:

```
...
                          {
                            "name": "tournaments",
                            "description": null,
                            "args": [
                                {
                                    "name": "query",
                                    "description": null,
                                    "type": {
                                        "kind": "NON_NULL",
                                        "name": null,
                                        "ofType": {
                                            "kind": "INPUT_OBJECT",
                                            "name": "TournamentsQuery",
                                            "ofType": null
                                        }
                                    },
                                    "defaultValue": null
                                },
                                {
                                    "name": "page",
                                    "description": null,
                                    "type": {
                                        "kind": "NON_NULL",
                                        "name": null,
                                        "ofType": {
                                            "kind": "INPUT_OBJECT",
                                            "name": "PageInfo",
                                            "ofType": null
                                        }
                                    },
                                    "defaultValue": null
                                }
                            ],
                            "type": {
                                "kind": "NON_NULL",
                                "name": null,
                                "ofType": {
                                    "kind": "OBJECT",
                                    "name": "Tournaments",
                                    "ofType": null
                                }
                            },
                            "isDeprecated": false,
                            "deprecationReason": null
                        },
...
```

For some reason, the generated code is:

```
...
class TournamentsFields(GraphQLField):
    @classmethod
    def edges(cls) -> "TournamentEdgeFields":
        return TournamentEdgeFields("edges")

    @classmethod
    def nodes(cls) -> "TournamentFields":
        return TournamentFields("nodes")

    @classmethod
    def page_info(cls) -> "ResponsePageInfoFields":
        return ResponsePageInfoFields("page_info")

    total_count: "TournamentsGraphQLField" = TournamentsGraphQLField("totalCount")

    def fields(
        self,
        *subfields: Union[
            TournamentsGraphQLField,
            "ResponsePageInfoFields",
            "TournamentEdgeFields",
            "TournamentFields",
        ]
    ) -> "TournamentsFields":
        """Subfields should come from the TournamentsFields class"""
        self._subfields.extend(subfields)
        return self

    def alias(self, alias: str) -> "TournamentsFields":
        self._alias = alias
        return self
...
```

ResponsePageInfoField("page_info") will result in an error as the api is expecting pageInfo instead of page_info. Any reason why some field names are generated this way ? How to prevent it ?

**Comment by RyPeck** [comment]
This looks like it was fixed in https://github.com/mirumee/ariadne-codegen/commit/11bfe35bd62b2489927e0e93c6891bccc29c7f37 but a new release was not created.

**Comment by flonou** [comment]
I'm not sure I followed the right step but I tried to remove ariadne-codgen with pip uninstall and install the last version with pip install git+https://github.com/mirumee/ariadne-codegen.git
and the issue is still present

**Comment by McleanWorkshield** [comment]
Came across the same issue and pulling from git worked. Don't forget to enable the setting in the pyproject file.

**Comment by flonou** [comment]
If I set convert_to_snake_case to true, both the fields and their fields names have _, if I set it to true, none of them has it.
I guess I'm missing something ? the fields names should never be changed from what the schema defines

**Comment by McleanWorkshield** [comment]
Maybe your scenario is different than mine - I actually do not want snake case, and `convert_to_snake_case` is true by default. To get mine to work, I actually set it to false and use camel case.

**Comment by flonou** [comment]
yeah I wanted snake_case for python variables but not for the field_names because that just doesn't follow the schema in that case

**Comment by davner** [comment]
@flonou I'm running into the same issue. 

```python


class UpdateProgramNotesResultFields(GraphQLField):
    @classmethod
    def program_notes(cls) -> "ProgramNoteFields":
        return ProgramNoteFields("program_notes")
```

should be 

```python


class UpdateProgramNotesResultFields(GraphQLField):
    @classmethod
    def program_notes(cls) -> "ProgramNoteFields":
        return ProgramNoteFields("programNotes")
```

This happens in numerous locations in the `custom_fields.py`. 

When I pull from git, the issue persists. This tool is great, and saves us a lot of development time with boilerplate code, I hope we can get this fixed and merged.

**Comment by flonou** [comment]
You can try my PR above to fix this

**Comment by davner** [comment]
I applied a plugin to patch those changes you made in #326 thanks for figuring that out. It is working as expected!

**Comment by ewen-lorimer** [comment]
Since #326 doesn't seem to be going anywhere I've just gone ahead and created a plugin that patches out this annoying behaviour. for anyone that would like to use it the plugin is called: [ariadne-codegen-field-fix](https://pypi.org/project/ariadne-codegen-field-fix/)
